services:
  jenkins_agent_windows:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE_FOR_JENKINS_AGENT_WINDOWS}
        JENKINS_URL: ${JENKINS_URL}
        SWARM_MASTER: "${SWARM_MASTER}"
        SWARM_USER: "${SWARM_USER}"
        SWARM_PASS: "${SWARM_PASS}"
        SWARM_EXECUTORS: "${SWARM_EXECUTORS}"
        LABELS: "${LABELS}"
        AGENT_NAME: "${AGENT_NAME}"
        JENKINS_AGENT_WORKSPACE: "${JENKINS_WORKSPACE}"

    volumes:
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine

    image: jenkins_agent_windows
