services:
  dev_tools_windows:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE_FOR_DEV_TOOLS_WINDOWS}
        P4_USER: ${PERFORCE_USERNAME}
        P4_PASS: ${PERFORCE_PASSWORD}
        P4_PORT: ${PERFORCE_PORT}
        P4_CLIENT: ${PERFORCE_CLIENT}
        P4_BASE_CLIENT: ${PERFORCE_BASE_CLIENT}
        P4_STREAM_GAME: ${PERFORCE_STREAM_GAME}
        P4_STREAM_ENGINE: ${PERFORCE_STREAM_ENGINE}
        P4_WORKSPACE: ${PERFORCE_WORKSPACE}
        ENGINE_DIR: ${ENGINE_DIR}
        PERFORCE_AGENT_WORKSPACE: ${PERFORCE_AGENT_WORKSPACE}
    image: dev_tools_windows
    container_name: dev_tools_windows
