name: Build and Push Android Docker Image of Jenkins Agent Running in windows targeted at android to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'images/docker/jenkins/agent/windows-runtime/android/**'
      - 'images/docker/jenkins/agent/windows-runtime/docker_layers/**'
  
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (default: staging)'
        required: false
        default: 'staging'

jobs:
  build-agent-windows-runtime:
    uses: ./.github/workflows/reusable-build-and-push-docker-images.yml
    with:
      dockerfile_dir: "images/docker/jenkins/agent/windows-runtime/android"
      image_config_file: 'images/docker/jenkins/agent/windows-runtime/android/image-config.yml'
      ansible_playbook_dir: 'configuration/ansible/playbooks/docker/jenkins/'
      ansible_playbook_file_name: 'build-push-docker-images.yml'
      ecr_repo: 'jenkins/agent/android'
      environment_name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' }}
    secrets:
      env_file_contents: ${{ secrets.ENV_FILE_CONTENTS_JENKINS_AGENT_WINDOWS_RUNTIME_ANDROID}}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
