name: Reusbale - Build and Push Jenkins Docker Images to ECR

on:
  workflow_call:
    inputs:
      dockerfile_dir:
        required: true
        type: string
        description: The directory containing the Dockerfile
      image_config_file:
        required: true
        type: string
        description: The file containing the image configuration
      ecr_repo:
        required: true
        type: string
        description: The ECR repository to push the image to
      ansible_playbook_dir:
        required: true
        type: string
        description: The directory where ansible playbook resides
      ansible_playbook_file_name:
        required: true
        type: string
        description: The file name(.yml) of the Ansible playbook to run
      env_file_contents:
        required: true
        type: string
        default: ""
        description: The contents of the .env file to create in the Docker build directory

jobs:
  build-and-push-docker-image-to-ecr:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment_name}}
    env:
      DOCKERFILE_DIR: ${{ inputs.dockerfile_dir }}
      IMAGE_CONFIG_FILE: ${{ inputs.image_config_file }} 
      ECR_REPO: ${{inputs.ecr_repo}}/${{inputs.environment_name}}
      ANSIBLE_PLAYBOOK_DIR: ${{ inputs.ansible_playbook_dir }}
      ANSIBLE_PLAYBOOK_FILE_NAME: ${{ inputs.ansible_playbook_file_name }}
      ENV_FILE_CONTENTS: ${{ inputs.env_file_contents }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Ansible and required collections
        run: |
          pip install --upgrade pip
          pip install ansible PyYAML
          PLAYBOOK_DIR=$(dirname "${{ env.ANSIBLE_PLAYBOOK_DIR}}")
          pip install -r "$PLAYBOOK_DIR/pip-requirements.txt"
          ansible-galaxy collection install -r "$PLAYBOOK_DIR/ansible-collections.yml"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Read image tag from config
        id: tag_config
        run: |
          TAG=$(python3 -c "import yaml; print(yaml.safe_load(open('${{ env.IMAGE_CONFIG_FILE }}'))['image_tag'])")
          echo "DOCKER_IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Run Ansible playbook to build and push agent image
        run: |
          ansible-playbook ${{ env.ANSIBLE_PLAYBOOK }} \
            --extra-vars "@$(dirname "${{ env.ANSIBLE_PLAYBOOK }}")/extra-vars.yml" -v
